<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! - Open Source Content Management" -->
<?xml-stylesheet href="http://waterboard.lk/web/plugins/system/osolcaptcha/osolCaptcha/captchaStyle.css" type="text/css"?>
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="en-gb">
	<title type="text">National Water Supply and Drainage Board
	<subtitle type="text">National Water Supply and Drainage Board</subtitle>
	<link rel="alternate" type="text/html" href="http://waterboard.lk"/>
	<id>http://waterboard.lk/web/index.php</id>
	<updated>2015-10-19T18:28:36+00:00</updated>
	<author>
		<name>National Water Supply and Drainage Board</name>
		<email>donotreply@waterboard.lk</email>
	</author>
	<generator uri="http://joomla.org">Joomla! - Open Source Content Management</generator>
	<link rel="self" type="application/atom+xml" href="http://waterboard.lk/web/index.php?option=com_content&amp;view=category&amp;id=41&amp;Itemid=101&amp;lang=en&amp;format=feed&amp;type=atom"/>
	<entry>
		<title>Central (Kandy, Matale and Nuwara Eliya Districts)
		<link rel="alternate" type="text/html" href="http://waterboard.lk/web/index.php?option=com_content&amp;view=article&amp;id=46&amp;catid=41&amp;Itemid=206&amp;lang=en"/>
		<published>2014-08-18T00:23:37+00:00</published>
		<updated>2014-08-18T00:23:37+00:00</updated>
		<id>http://waterboard.lk/web/index.php?option=com_content&amp;view=article&amp;id=46&amp;catid=41&amp;Itemid=206&amp;lang=en</id>
		<author>
			<name>piyo</name>
			<email>test@maoil.com</email>
		</author>
		<summary type="html">&lt;p style=&quot;text-align: justify;&quot;&gt;Central RSC has been functioning since 1987. This is one of the first RSCs that became operational after the NWSDB decided to decentralize its operations. As per the norm. a Deputy General Manager (DGM) is heading the Central RSC. He is supported by an Assistant General Manager (AGM) and other managers in carrying out the administrative and operational functions. This RSC has three regions “Kandy East”, ”Kandy South” and ”Kandy North”. The O&amp;amp;M is under the supervision of the respective regional manager. The most important of the RSC functions is the O&amp;amp;M of water supply schemes. O &amp;amp; M of the only sewerage system in Kandy Hantana area is also the responsibility of the Kandy East regional manager. Other key functions of RSC are: (a) planning and design works related to Local Projects; (b) planning work related to large projects; (c) implementation of rehabilitation and augmentation works of the existing schemes; and (d) billing and revenue collection.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;The operations of the Central RSC is monitored and supervised by the Additional General Manager (Central and North) who is stationed in Colombo Head Office. The day to day management of the RSC rests entirely on the DGM and all the managers reporting to him following the hierarchical institutional structure. In general, various Divisions found in the Head Office are represented in the RSC as units. The strengths of such units depend on the degree of decentralization that has taken place. The Central RSC is also providing support services to other RSCs upon request and most of such requests are coordinated by the Additional General Manager (Central &amp;amp; North).&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;

<div class="nn_sliders accordion panel-group" id="set-nn_sliders-1">
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-1" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#location-of-the-area"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Location of the Area
</span></a>
</div>
<div class="accordion-body collapse" id="location-of-the-area">
<div class="accordion-inner panel-body">&lt;/p&gt;
&lt;table style=&quot;width: 100%;&quot;&gt;
&lt;tbody&gt;
&lt;tr valign=&quot;top&quot;&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;&lt;a href=&quot;http://waterboard.lk/web/images/contents/regional_support_centres/central/central_map.png&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;http://waterboard.lk/web/images/contents/regional_support_centres/central/central_map.png&quot; alt=&quot;central map&quot; width=&quot;350&quot; height=&quot;233&quot; /&gt;&lt;/a&gt;&lt;br /&gt;&lt;em&gt;Please click on map to enlarge it&lt;/em&gt;&lt;/td&gt;
&lt;td&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Statistics of the Area&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Total Area&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;5,674.0&amp;nbsp;km2&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Population (2001)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;2,423,966&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Population (2011)*&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;2,558,574&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Population Density (2011)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;451&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
* &lt;em&gt;Population by the Department of Census and Statistics - Sri Lanka&lt;/em&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Click on below links to View or Download the original map published by the Survey Department of the Government of Sri Lanka.&lt;/p&gt;
&lt;ul class=&quot;pdf&quot;&gt;
&lt;li style=&quot;text-align: justify;&quot;&gt;&lt;a href=&quot;http://waterboard.lk/web/images/contents/regional_support_centres/central/kandy_district_map.pdf&quot; target=&quot;_blank&quot;&gt;Kandy District Map&lt;br /&gt;[ PDF - 453 KB ]&lt;/a&gt;&lt;/li&gt;
&lt;li style=&quot;text-align: justify;&quot;&gt;&lt;a href=&quot;http://waterboard.lk/web/images/contents/regional_support_centres/central/matale_district_map.pdf&quot; target=&quot;_blank&quot;&gt;Matale District Map&lt;br /&gt;[ PDF - 345 KB ]&lt;/a&gt;&lt;/li&gt;
&lt;li style=&quot;text-align: justify;&quot;&gt;&lt;a href=&quot;http://waterboard.lk/web/images/contents/regional_support_centres/central/nuwaraeliya_district_map.pdf&quot; target=&quot;_blank&quot;&gt;Nuwara Eliya District Map&lt;br /&gt;[ PDF - 438 KB ]&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt;

</div></div></div>
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-1" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#comparison-of-service-connections"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Comparison of Service Connections
</span></a>
</div>
<div class="accordion-body collapse" id="comparison-of-service-connections">
<div class="accordion-inner panel-body">&lt;/p&gt;
&lt;table style=&quot;height: 216px; width: 692px;&quot; border=&quot;0&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;&lt;strong&gt;As at end of&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;No.of Connection&lt;/strong&gt;&lt;/td&gt;
&lt;td rowspan=&quot;10&quot;&gt;&lt;img style=&quot;display: block; margin-left: auto; margin-right: auto;&quot; src=&quot;http://waterboard.lk/web/images/contents/regional_support_centres/central/central.jpg&quot; alt=&quot;central&quot; /&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;2006&lt;/td&gt;
&lt;td&gt;113,711&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;2007&lt;/td&gt;
&lt;td&gt;128,029&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;2008&lt;/td&gt;
&lt;td&gt;139,414&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;2009&lt;/td&gt;
&lt;td&gt;148,470&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;2010&lt;/td&gt;
&lt;td&gt;164,259&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;2011&lt;/td&gt;
&lt;td&gt;179,840&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;2012&lt;/td&gt;
&lt;td&gt;198,667&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;2013&lt;/td&gt;
&lt;td&gt;211,936&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;2014&lt;/td&gt;
&lt;td&gt;224,217&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;

</div></div></div>
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-1" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#details-of-schemes-within-the-area"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Details of Schemes within the area
</span></a>
</div>
<div class="accordion-body collapse" id="details-of-schemes-within-the-area">
<div class="accordion-inner panel-body">&lt;/p&gt;
&lt;p&gt;The quality of water being supplied is tested regularly. &lt;a href=&quot;http://waterboard.lk/web/index.php?option=com_content&amp;amp;view=article&amp;amp;id=68&amp;amp;Itemid=273&amp;amp;lang=en&quot;&gt;Click here&lt;/a&gt; for a summary of test results taken island-wide.&lt;/p&gt;
&lt;h4&gt;Schemes which are presently in operation&lt;/h4&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;Region&lt;/td&gt;
&lt;td&gt;Integrated Scheme&lt;/td&gt;
&lt;td&gt;Total no. of connections as end of 31st December 2014&lt;/td&gt;
&lt;td&gt;Average Monthly Production (m3/ month)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td rowspan=&quot;16&quot;&gt;Kandy District&lt;/td&gt;
&lt;td&gt;Akurana&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;11,894&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;254,394&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Ankumbura&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;961&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;6,650&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Galagedara&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;1,894&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;32,249&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Harispaththuwa&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;14,740&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;293,891&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Kandy MC(bulk)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;bulk&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;332,536&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Pathadumbara&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;16,152&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;284,275&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Poojapitiya&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,371&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;61,234&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Gampola&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;18,068&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;308,600&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Nawalapitiya&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,562&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;89,981&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Udu/Yatinuwara&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;49,013&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;917,092&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;University&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;1&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;149,750&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Ampitiya&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;5,994&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;116,048&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Hantana&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;589&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;14,229&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Kundasale/Haragama&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;36,028&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;693,439&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Medadumbara&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;5,686&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;93,774&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Marassana&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,869&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;83,794&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td class=&quot;r2&quot; rowspan=&quot;3&quot;&gt;Matale District&lt;/td&gt;
&lt;td&gt;Dambulla&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,153&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;105,283&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Matale&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;27,144&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;626,658&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Naula&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2,376&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;46,601&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td class=&quot;r1&quot; rowspan=&quot;5&quot;&gt;Nuwara Eliya District&lt;/td&gt;
&lt;td&gt;Ginigathhena/Poondaluoya&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;1,823&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;29,438&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Hatton&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,501&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;81,109&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Maskeliya&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2,722&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;41,938&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Rikillagaskada&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,142&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;58,016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Walapane/Ragala&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2,534&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;42,723&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Total&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;224,217&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,756,745&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Ongoing Projects&lt;/h4&gt;
&lt;h5&gt;Small and Medium Water Supply Projects&lt;/h5&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td rowspan=&quot;2&quot;&gt;Project Name&lt;/td&gt;
&lt;td style=&quot;width: 75px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;No. of Beneficiaries&lt;/td&gt;
&lt;td style=&quot;width: 110px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;Total Cost Estimate&lt;br /&gt;(Rs. Million)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Duration&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;From&lt;/td&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;To&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Marassana Water Supply&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;25,000&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;339&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jan 1996&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Dec 2015&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Thalawakele/ Lindula Water Supply&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;15,000&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;352&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jan 2000&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jan 2016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Kundasale Integrated Water Supply&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;130,000&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;1685&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jan 1998&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Dec 2016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Matale Water Supply&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;142,800&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;525&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jan 1999&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Dec 2015&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h5&gt;Large Scale Sewerage Projects&lt;/h5&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td rowspan=&quot;2&quot;&gt;Project Name (Donor)&lt;/td&gt;
&lt;td style=&quot;width: 75px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;No. of Beneficiaries&lt;/td&gt;
&lt;td style=&quot;width: 110px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;Total Cost Estimate&lt;br /&gt;(Rs. Million)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Duration&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;From&lt;/td&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;To&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Sector Development Project I Sub Project &amp;nbsp;- Sewerage Disposal System for Kandy Municipal Area Consultancy (JBIC)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;55,000+150,000 migrants&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;21,982&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;July 2010&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2018&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h5 style=&quot;line-height: 15.8079996109009px;&quot;&gt;Large Scale Water Supply and Sanitation Projects&lt;/h5&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 678px;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td rowspan=&quot;2&quot;&gt;Project Name (Donor)&lt;/td&gt;
&lt;td style=&quot;width: 75px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;No. of Beneficiaries&lt;/td&gt;
&lt;td style=&quot;width: 110px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;Total Cost Estimate&lt;br /&gt;(Rs. Million)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Duration&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;From&lt;/td&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;To&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Sector Development Project I Sub Project IV - Greater Kandy Water Supply Water Supply Phase I Stage II (JBIC)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;249,500&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,200&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Mar 2007&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2015&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&amp;nbsp;Greater Dambulla Water Supply - Stage I(India)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;120,000&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;10,700&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2012&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;&amp;nbsp;2015&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h5&gt;&lt;strong&gt;Local Bank Funded Projects&lt;/strong&gt;&lt;/h5&gt;
&lt;table style=&quot;height: 134px; width: 682px;&quot; border=&quot;0&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;Project Name&lt;/td&gt;
&lt;td&gt;No.of Beneficiaries&lt;/td&gt;
&lt;td&gt;Total Cost Estimate (R. Million)&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;Duration&lt;/p&gt;
&lt;p&gt;From - To&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Kotmale River Side WSP&lt;/td&gt;
&lt;td&gt;18,000&lt;/td&gt;
&lt;td&gt;2,874&lt;/td&gt;
&lt;td&gt;2015 - 2017&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Wilgamuwa Heenganga WSP&lt;/td&gt;
&lt;td&gt;25,000&lt;/td&gt;
&lt;td&gt;3,754&lt;/td&gt;
&lt;td&gt;2014 - 2016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Laggala-Pallegama WSP&lt;/td&gt;
&lt;td&gt;32,000&lt;/td&gt;
&lt;td&gt;4,623&lt;/td&gt;
&lt;td&gt;2014 - 2016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Pathahewaheta WSP&lt;/td&gt;
&lt;td&gt;10,328&lt;/td&gt;
&lt;td&gt;678&lt;/td&gt;
&lt;td&gt;2014 - 2016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Hasalaka WSP&lt;/td&gt;
&lt;td&gt;49,370&lt;/td&gt;
&lt;td&gt;5,470&lt;/td&gt;
&lt;td&gt;2015 - 2017&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h5&gt;&amp;nbsp;&lt;/h5&gt;
&lt;h5&gt;Large Scale Sewerage Projects&lt;/h5&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td rowspan=&quot;2&quot;&gt;Project Name (Donor)&lt;/td&gt;
&lt;td style=&quot;width: 75px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;No. of Beneficiaries&lt;/td&gt;
&lt;td style=&quot;width: 110px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;Total Cost Estimate&lt;br /&gt;(Rs. Million)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Duration&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;From&lt;/td&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;To&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Sector Development Project I Sub Project I Sewage Disposal System for Kandy Municipal Area Consultancy (JBIC)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;5,500+150,000 migrants&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;21,982&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jul 2010&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2018&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;

</div></div></div>
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-1" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#contact-details"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Contact Details
</span></a>
</div>
<div class="accordion-body collapse" id="contact-details">
<div class="accordion-inner panel-body">&lt;/p&gt;
&lt;p&gt;Please &lt;a href=&quot;http://waterboard.lk/web/images/contents/regional_support_centres/central/contacts_central.pdf&quot; target=&quot;_blank&quot;&gt;click here&lt;/a&gt; to view / download full contact list for Regional Support Centre (Central)&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr valign=&quot;top&quot;&gt;
&lt;td&gt;&lt;strong&gt;Postal Address&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;:&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;Regional Support Centre (Central)&lt;br /&gt;National Water Supply &amp;amp; Drainage Board&lt;br /&gt;Gatambe, Peradeniya&lt;/td&gt;
&lt;/tr&gt;
&lt;tr valign=&quot;top&quot;&gt;
&lt;td&gt;&lt;strong&gt;Telephone / Fax&lt;br /&gt;&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;:&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;+94 81 2388086, +94 81 2388027&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;table class=&quot;mtable conname&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;Name &amp;amp; Designation&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;Telephone / Fax&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;Mobile&lt;/td&gt;
&lt;td&gt;E-mail&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. L.L.A. Peiris&lt;/strong&gt;&lt;br /&gt;Deputy General Manager&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2387149&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 7585400&lt;/td&gt;
&lt;td&gt;dgm_central@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. J.H. Meegoda&lt;/strong&gt;&lt;br /&gt;Assistant General Manager&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;
&lt;p&gt;+94 81 2384176,&lt;br /&gt;+94 81 2386667,&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Toll Free No:&amp;nbsp;&lt;/strong&gt;+94 81 2384400&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 7845535&lt;/td&gt;
&lt;td&gt;agm_central@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Managers (Operational &amp;amp; Maintenance)&lt;/h4&gt;
&lt;table class=&quot;mtable conname&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;Name &amp;amp; Designation&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;Telephone / Fax&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;Mobile&lt;/td&gt;
&lt;td&gt;E-mail&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr.&amp;nbsp;&lt;strong style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;N. Chandrasena&lt;/strong&gt;&lt;/strong&gt;&lt;br /&gt;(Kandy - South)&lt;br /&gt;&lt;em&gt;&lt;strong&gt;Responsive Areas:&lt;/strong&gt;&lt;/em&gt; University, Udunuwara, Yatinuwara, Eriyagama, Kadugannawa, Gampola, Nawalapitiya, Nillambe, Weligalla WSS&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2389077&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal; text-align: center;&quot;&gt;+94 71 8196194&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;m_ks_central@waterboard.lk&lt;/span&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. S. Piyaratne&lt;/strong&gt;&lt;br /&gt;(Kandy - North)&lt;br /&gt;&lt;em&gt;&lt;strong&gt;Responsive Areas:&lt;/strong&gt;&lt;/em&gt; Harispaththuwa, Alawathugoda, Akurana, Galagedara, Pathadumbara WSS&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2492302,&lt;br /&gt;&lt;strong&gt;Fax:&amp;nbsp;&lt;/strong&gt;+94 81 2492303&lt;br /&gt;&lt;strong&gt;Toll Free No:&lt;/strong&gt; +94 81 2492222&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 7223738&lt;/td&gt;
&lt;td&gt;m_kn_central@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. I.C.B. Vithanage&lt;/strong&gt;&lt;br /&gt;(Kandy - East)&lt;br /&gt;&lt;em&gt;&lt;strong&gt;Responsive Areas:&lt;/strong&gt;&lt;/em&gt; Kundasale, Marassana, Tennekumbura, Medadumbara, Hantana, Ampitiyam, Rikillagaskada, Walapane, Ragala, Hatton, Maskeliya, Ginigathhena, Thalawakele, Kotagala, Poondaluoya WSS&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2420585&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 71 4198416&lt;/td&gt;
&lt;td&gt;m_ke_central@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Mr. S.M.S. Bandara&lt;/strong&gt;&lt;br style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot; /&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;(Production)&lt;/span&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2492300 &amp;nbsp; &lt;strong&gt;Fax:&lt;/strong&gt; +94 81 2492222&amp;nbsp;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 71 4814576&amp;nbsp;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. W. Jayasinghe&lt;/strong&gt;&lt;br /&gt;Manager (Human resources)&lt;br /&gt;&lt;em&gt;&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/em&gt;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2385602,&lt;br /&gt;&lt;strong&gt;Fax:&amp;nbsp;&lt;/strong&gt;+94 81 2386667&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 2442058&lt;/td&gt;
&lt;td&gt;mssc@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. R.A.C. Ariyaratne&lt;/strong&gt;&lt;br /&gt;Manager (Commercial)&lt;br /&gt;&lt;em&gt;&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/em&gt;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2385602,&lt;br /&gt;&lt;strong&gt;Fax:&lt;/strong&gt;+94 81 2386667&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 7764349, +94 71 6821598&amp;nbsp;&lt;/td&gt;
&lt;td&gt;m_co_central@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Other Sections&lt;/h4&gt;
&lt;table class=&quot;mtable conname&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;Name &amp;amp; Designation&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;Telephone / Fax&lt;/td&gt;
&lt;td style=&quot;width: 60px; text-align: center;&quot;&gt;Mobile&lt;/td&gt;
&lt;td&gt;E-mail&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mrs. N.K.B.C.D. Narasinghe&lt;/strong&gt;&lt;br /&gt;Chief Engineer (Planning &amp;amp; Design)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2374528,&lt;br /&gt;+94 81 2386667&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 71 4426923&lt;/td&gt;
&lt;td&gt;cepndcentral@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. A.M.A.M. Adikari&lt;/strong&gt;&lt;br /&gt;Chief Engineer (Development)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2387175,&lt;br /&gt;+94 81 2388027&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 071 4825182&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. H.P.K.S. Pathirana&lt;/strong&gt;&lt;br /&gt;Chief Engineer (Contruction)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2374528,&lt;br /&gt;+94 81 2386667&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 71 8298570&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. P.V.J. Fernando&lt;/strong&gt;&lt;br /&gt;Chief Engineer (Mechanical &amp;amp; Electrical)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2387175,&lt;br /&gt;+94 81 2386667&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 34007394, +94 71 4394898&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;&lt;strong style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Mr. W. Jayasinghe&lt;/strong&gt;&lt;br style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot; /&gt;&lt;/strong&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Chief Engineer (Sector Planning)&lt;/span&gt;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal; text-align: center;&quot;&gt;+94 81 23888962,&lt;/span&gt;&lt;br style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal; text-align: center;&quot; /&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal; text-align: center;&quot;&gt;+94 81 2386667&lt;/span&gt;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal; text-align: center;&quot;&gt;+94 77 2442058&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;mailto:sectorplan@hotmail.com&quot;&gt;sectorplan@hotmail.com&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;

</div></div></div>
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-1" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#key-facts-and-figures"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Key Facts and Figures
</span></a>
</div>
<div class="accordion-body collapse" id="key-facts-and-figures">
<div class="accordion-inner panel-body">&lt;/p&gt;
&lt;h4&gt;Service Standard Indicators&lt;/h4&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; rowspan=&quot;2&quot;&gt;Service Indicators&amp;nbsp;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;RSC (Central) 2014' Dec&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center; width: 200px;&quot;&gt;Regional Average&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Coverage (%) Pipe System maintained by NWSDB&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;36%&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Per Capita Consumption (l/c/d)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;108.83&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Availability (hours)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;20.3&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Water Quality - Bacteriological Quality Compliance&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Quality - Bacteriological Testing Compliance&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Water Quality - All Samples Compliance&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Sewerage Coverage (%)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;0.10%&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Operational Indicators&lt;/h4&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; rowspan=&quot;2&quot;&gt;Operational Indicators&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;RSC (Central) 2014'Aug&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center; width: 200px;&quot;&gt;Regional Average&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Non-Revenue Water (%)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;24%&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Non-Revenue Water - m&lt;sup&gt;3&lt;/sup&gt;/conn/day&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;0.17&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Defective Meters per '000 connections (Monthly Average)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;0&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Total Staff/ 1000 connection&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;3.93&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Operational Staff/ 1000 connection&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;3.25&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Estimated Bills/ 1000 connections (Monthly Average)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;1&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Performance in Customer Service&lt;/h4&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; rowspan=&quot;2&quot;&gt;Customer Service Indicators&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;RSC (Central) 2014'Aug&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center; width: 200px;&quot;&gt;Regional Average&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Response to requests for new service connections (%)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;100.0%&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Customer Complaints Volume (Complaints/ 1000 connection)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;28&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Customer Complaints Resolution&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;100%&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Key Performance Indicators (KPIs)&lt;/h4&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; rowspan=&quot;2&quot;&gt;Financial KPIs&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;RSC (Central) 2014'Aug&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center; width: 200px;&quot;&gt;Regional Average&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Collection Ratio (%)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;96.0%&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Accounts Receivable Period (months)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;2.1&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Collectable Accounts Receivable Period (months)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;0.95&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Operating Ratio&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;1.08&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Production Cost (LKR/ m3 Produced) (Only operational cost)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;31.9&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Average Tariff (LKR/ m&lt;sup&gt;3&lt;/sup&gt; Sold)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;37&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Stock Efficiency (LKR/ connection)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;3,595&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 15.8079996109009px;&quot;&gt;

</div></div></div>
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-1" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#large-scale-water-supply-amp-sanitation-projects"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Large Scale Water Supply &amp;amp; Sanitation Projects
</span></a>
</div>
<div class="accordion-body collapse" id="large-scale-water-supply-amp-sanitation-projects">
<div class="accordion-inner panel-body">&lt;/span&gt;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;Project Name&amp;nbsp;&lt;/td&gt;
&lt;td&gt;No of Beneficiaries&amp;nbsp;&lt;/td&gt;
&lt;td&gt;Total Cost Estimate (Rs.Million)&amp;nbsp;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;From&lt;/td&gt;
&lt;td&gt;To&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&amp;nbsp;Gr. Kandy Water Supply Project (pha 1, Stg 2)&lt;/td&gt;
&lt;td&gt;249,500&amp;nbsp;&lt;/td&gt;
&lt;td&gt;4,200&amp;nbsp;&lt;/td&gt;
&lt;td&gt;March 2007&amp;nbsp;&lt;/td&gt;
&lt;td&gt;2015&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Gr. Dambulla Water Supply Project&amp;nbsp;&lt;/td&gt;
&lt;td&gt;120,000&lt;/td&gt;
&lt;td&gt;10,700&amp;nbsp;&lt;/td&gt;
&lt;td&gt;2015&amp;nbsp;&lt;/td&gt;
&lt;td&gt;2015&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Gr. Matale&amp;nbsp;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Water Supply Project&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;393,317&amp;nbsp;&lt;/td&gt;
&lt;td&gt;26,834&amp;nbsp;&lt;/td&gt;
&lt;td&gt;2015&amp;nbsp;&lt;/td&gt;
&lt;td&gt;2018&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Kand North Pathadumbara&amp;nbsp;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Water Supply Project&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;470,000&lt;/td&gt;
&lt;td&gt;33,400&lt;/td&gt;
&lt;td&gt;2015&lt;/td&gt;
&lt;td&gt;2018&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;</div></div></div></div>&lt;/p&gt;</summary>
		<content type="html">&lt;p style=&quot;text-align: justify;&quot;&gt;Central RSC has been functioning since 1987. This is one of the first RSCs that became operational after the NWSDB decided to decentralize its operations. As per the norm. a Deputy General Manager (DGM) is heading the Central RSC. He is supported by an Assistant General Manager (AGM) and other managers in carrying out the administrative and operational functions. This RSC has three regions “Kandy East”, ”Kandy South” and ”Kandy North”. The O&amp;amp;M is under the supervision of the respective regional manager. The most important of the RSC functions is the O&amp;amp;M of water supply schemes. O &amp;amp; M of the only sewerage system in Kandy Hantana area is also the responsibility of the Kandy East regional manager. Other key functions of RSC are: (a) planning and design works related to Local Projects; (b) planning work related to large projects; (c) implementation of rehabilitation and augmentation works of the existing schemes; and (d) billing and revenue collection.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;The operations of the Central RSC is monitored and supervised by the Additional General Manager (Central and North) who is stationed in Colombo Head Office. The day to day management of the RSC rests entirely on the DGM and all the managers reporting to him following the hierarchical institutional structure. In general, various Divisions found in the Head Office are represented in the RSC as units. The strengths of such units depend on the degree of decentralization that has taken place. The Central RSC is also providing support services to other RSCs upon request and most of such requests are coordinated by the Additional General Manager (Central &amp;amp; North).&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;

<div class="nn_sliders accordion panel-group" id="set-nn_sliders-2">
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-2" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#location-of-the-area-2"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Location of the Area
</span></a>
</div>
<div class="accordion-body collapse" id="location-of-the-area-2">
<div class="accordion-inner panel-body">&lt;/p&gt;
&lt;table style=&quot;width: 100%;&quot;&gt;
&lt;tbody&gt;
&lt;tr valign=&quot;top&quot;&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;&lt;a href=&quot;images/contents/regional_support_centres/central/central_map.png&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;images/contents/regional_support_centres/central/central_map.png&quot; alt=&quot;central map&quot; width=&quot;350&quot; height=&quot;233&quot; /&gt;&lt;/a&gt;&lt;br /&gt;&lt;em&gt;Please click on map to enlarge it&lt;/em&gt;&lt;/td&gt;
&lt;td&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Statistics of the Area&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Total Area&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;5,674.0&amp;nbsp;km2&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Population (2001)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;2,423,966&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Population (2011)*&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;2,558,574&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Population Density (2011)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;451&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
* &lt;em&gt;Population by the Department of Census and Statistics - Sri Lanka&lt;/em&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Click on below links to View or Download the original map published by the Survey Department of the Government of Sri Lanka.&lt;/p&gt;
&lt;ul class=&quot;pdf&quot;&gt;
&lt;li style=&quot;text-align: justify;&quot;&gt;&lt;a href=&quot;images/contents/regional_support_centres/central/kandy_district_map.pdf&quot; target=&quot;_blank&quot;&gt;Kandy District Map&lt;br /&gt;[ PDF - 453 KB ]&lt;/a&gt;&lt;/li&gt;
&lt;li style=&quot;text-align: justify;&quot;&gt;&lt;a href=&quot;images/contents/regional_support_centres/central/matale_district_map.pdf&quot; target=&quot;_blank&quot;&gt;Matale District Map&lt;br /&gt;[ PDF - 345 KB ]&lt;/a&gt;&lt;/li&gt;
&lt;li style=&quot;text-align: justify;&quot;&gt;&lt;a href=&quot;images/contents/regional_support_centres/central/nuwaraeliya_district_map.pdf&quot; target=&quot;_blank&quot;&gt;Nuwara Eliya District Map&lt;br /&gt;[ PDF - 438 KB ]&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt;

</div></div></div>
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-2" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#comparison-of-service-connections-2"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Comparison of Service Connections
</span></a>
</div>
<div class="accordion-body collapse" id="comparison-of-service-connections-2">
<div class="accordion-inner panel-body">&lt;/p&gt;
&lt;table style=&quot;height: 216px; width: 692px;&quot; border=&quot;0&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;&lt;strong&gt;As at end of&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;No.of Connection&lt;/strong&gt;&lt;/td&gt;
&lt;td rowspan=&quot;10&quot;&gt;&lt;img style=&quot;display: block; margin-left: auto; margin-right: auto;&quot; src=&quot;images/contents/regional_support_centres/central/central.jpg&quot; alt=&quot;central&quot; /&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;2006&lt;/td&gt;
&lt;td&gt;113,711&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;2007&lt;/td&gt;
&lt;td&gt;128,029&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;2008&lt;/td&gt;
&lt;td&gt;139,414&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;2009&lt;/td&gt;
&lt;td&gt;148,470&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;2010&lt;/td&gt;
&lt;td&gt;164,259&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;2011&lt;/td&gt;
&lt;td&gt;179,840&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;2012&lt;/td&gt;
&lt;td&gt;198,667&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;2013&lt;/td&gt;
&lt;td&gt;211,936&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;2014&lt;/td&gt;
&lt;td&gt;224,217&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;

</div></div></div>
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-2" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#details-of-schemes-within-the-area-2"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Details of Schemes within the area
</span></a>
</div>
<div class="accordion-body collapse" id="details-of-schemes-within-the-area-2">
<div class="accordion-inner panel-body">&lt;/p&gt;
&lt;p&gt;The quality of water being supplied is tested regularly. &lt;a href=&quot;index.php?option=com_content&amp;amp;view=article&amp;amp;id=68&amp;amp;Itemid=273&amp;amp;lang=en&quot;&gt;Click here&lt;/a&gt; for a summary of test results taken island-wide.&lt;/p&gt;
&lt;h4&gt;Schemes which are presently in operation&lt;/h4&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;Region&lt;/td&gt;
&lt;td&gt;Integrated Scheme&lt;/td&gt;
&lt;td&gt;Total no. of connections as end of 31st December 2014&lt;/td&gt;
&lt;td&gt;Average Monthly Production (m3/ month)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td rowspan=&quot;16&quot;&gt;Kandy District&lt;/td&gt;
&lt;td&gt;Akurana&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;11,894&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;254,394&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Ankumbura&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;961&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;6,650&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Galagedara&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;1,894&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;32,249&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Harispaththuwa&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;14,740&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;293,891&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Kandy MC(bulk)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;bulk&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;332,536&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Pathadumbara&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;16,152&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;284,275&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Poojapitiya&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,371&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;61,234&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Gampola&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;18,068&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;308,600&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Nawalapitiya&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,562&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;89,981&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Udu/Yatinuwara&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;49,013&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;917,092&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;University&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;1&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;149,750&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Ampitiya&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;5,994&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;116,048&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Hantana&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;589&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;14,229&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Kundasale/Haragama&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;36,028&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;693,439&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Medadumbara&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;5,686&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;93,774&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Marassana&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,869&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;83,794&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td class=&quot;r2&quot; rowspan=&quot;3&quot;&gt;Matale District&lt;/td&gt;
&lt;td&gt;Dambulla&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,153&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;105,283&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Matale&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;27,144&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;626,658&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Naula&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2,376&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;46,601&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td class=&quot;r1&quot; rowspan=&quot;5&quot;&gt;Nuwara Eliya District&lt;/td&gt;
&lt;td&gt;Ginigathhena/Poondaluoya&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;1,823&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;29,438&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Hatton&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,501&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;81,109&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Maskeliya&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2,722&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;41,938&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Rikillagaskada&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,142&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;58,016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Walapane/Ragala&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2,534&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;42,723&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Total&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;224,217&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,756,745&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Ongoing Projects&lt;/h4&gt;
&lt;h5&gt;Small and Medium Water Supply Projects&lt;/h5&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td rowspan=&quot;2&quot;&gt;Project Name&lt;/td&gt;
&lt;td style=&quot;width: 75px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;No. of Beneficiaries&lt;/td&gt;
&lt;td style=&quot;width: 110px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;Total Cost Estimate&lt;br /&gt;(Rs. Million)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Duration&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;From&lt;/td&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;To&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Marassana Water Supply&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;25,000&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;339&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jan 1996&amp;nbsp;&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Dec 2015&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Thalawakele/ Lindula Water Supply&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;15,000&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;352&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jan 2000&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jan 2016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Kundasale Integrated Water Supply&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;130,000&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;1685&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jan 1998&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Dec 2016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Matale Water Supply&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;142,800&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;525&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jan 1999&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Dec 2015&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h5&gt;Large Scale Sewerage Projects&lt;/h5&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td rowspan=&quot;2&quot;&gt;Project Name (Donor)&lt;/td&gt;
&lt;td style=&quot;width: 75px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;No. of Beneficiaries&lt;/td&gt;
&lt;td style=&quot;width: 110px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;Total Cost Estimate&lt;br /&gt;(Rs. Million)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Duration&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;From&lt;/td&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;To&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Sector Development Project I Sub Project &amp;nbsp;- Sewerage Disposal System for Kandy Municipal Area Consultancy (JBIC)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;55,000+150,000 migrants&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;21,982&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;July 2010&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2018&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h5 style=&quot;line-height: 15.8079996109009px;&quot;&gt;Large Scale Water Supply and Sanitation Projects&lt;/h5&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 678px;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td rowspan=&quot;2&quot;&gt;Project Name (Donor)&lt;/td&gt;
&lt;td style=&quot;width: 75px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;No. of Beneficiaries&lt;/td&gt;
&lt;td style=&quot;width: 110px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;Total Cost Estimate&lt;br /&gt;(Rs. Million)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Duration&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;From&lt;/td&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;To&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Sector Development Project I Sub Project IV - Greater Kandy Water Supply Water Supply Phase I Stage II (JBIC)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;249,500&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;4,200&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Mar 2007&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2015&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&amp;nbsp;Greater Dambulla Water Supply - Stage I(India)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;120,000&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;10,700&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2012&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;&amp;nbsp;2015&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h5&gt;&lt;strong&gt;Local Bank Funded Projects&lt;/strong&gt;&lt;/h5&gt;
&lt;table style=&quot;height: 134px; width: 682px;&quot; border=&quot;0&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;Project Name&lt;/td&gt;
&lt;td&gt;No.of Beneficiaries&lt;/td&gt;
&lt;td&gt;Total Cost Estimate (R. Million)&lt;/td&gt;
&lt;td&gt;
&lt;p&gt;Duration&lt;/p&gt;
&lt;p&gt;From - To&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Kotmale River Side WSP&lt;/td&gt;
&lt;td&gt;18,000&lt;/td&gt;
&lt;td&gt;2,874&lt;/td&gt;
&lt;td&gt;2015 - 2017&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Wilgamuwa Heenganga WSP&lt;/td&gt;
&lt;td&gt;25,000&lt;/td&gt;
&lt;td&gt;3,754&lt;/td&gt;
&lt;td&gt;2014 - 2016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Laggala-Pallegama WSP&lt;/td&gt;
&lt;td&gt;32,000&lt;/td&gt;
&lt;td&gt;4,623&lt;/td&gt;
&lt;td&gt;2014 - 2016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Pathahewaheta WSP&lt;/td&gt;
&lt;td&gt;10,328&lt;/td&gt;
&lt;td&gt;678&lt;/td&gt;
&lt;td&gt;2014 - 2016&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Hasalaka WSP&lt;/td&gt;
&lt;td&gt;49,370&lt;/td&gt;
&lt;td&gt;5,470&lt;/td&gt;
&lt;td&gt;2015 - 2017&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h5&gt;&amp;nbsp;&lt;/h5&gt;
&lt;h5&gt;Large Scale Sewerage Projects&lt;/h5&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td rowspan=&quot;2&quot;&gt;Project Name (Donor)&lt;/td&gt;
&lt;td style=&quot;width: 75px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;No. of Beneficiaries&lt;/td&gt;
&lt;td style=&quot;width: 110px; text-align: center;&quot; rowspan=&quot;2&quot;&gt;Total Cost Estimate&lt;br /&gt;(Rs. Million)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot; colspan=&quot;2&quot;&gt;Duration&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;From&lt;/td&gt;
&lt;td style=&quot;width: 50px; text-align: center;&quot;&gt;To&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Sector Development Project I Sub Project I Sewage Disposal System for Kandy Municipal Area Consultancy (JBIC)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;5,500+150,000 migrants&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;21,982&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;Jul 2010&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;2018&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;

</div></div></div>
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-2" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#contact-details-2"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Contact Details
</span></a>
</div>
<div class="accordion-body collapse" id="contact-details-2">
<div class="accordion-inner panel-body">&lt;/p&gt;
&lt;p&gt;Please &lt;a href=&quot;images/contents/regional_support_centres/central/contacts_central.pdf&quot; target=&quot;_blank&quot;&gt;click here&lt;/a&gt; to view / download full contact list for Regional Support Centre (Central)&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr valign=&quot;top&quot;&gt;
&lt;td&gt;&lt;strong&gt;Postal Address&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;:&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;Regional Support Centre (Central)&lt;br /&gt;National Water Supply &amp;amp; Drainage Board&lt;br /&gt;Gatambe, Peradeniya&lt;/td&gt;
&lt;/tr&gt;
&lt;tr valign=&quot;top&quot;&gt;
&lt;td&gt;&lt;strong&gt;Telephone / Fax&lt;br /&gt;&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&lt;strong&gt;:&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;+94 81 2388086, +94 81 2388027&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;table class=&quot;mtable conname&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;Name &amp;amp; Designation&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;Telephone / Fax&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;Mobile&lt;/td&gt;
&lt;td&gt;E-mail&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. L.L.A. Peiris&lt;/strong&gt;&lt;br /&gt;Deputy General Manager&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2387149&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 7585400&lt;/td&gt;
&lt;td&gt;dgm_central@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. J.H. Meegoda&lt;/strong&gt;&lt;br /&gt;Assistant General Manager&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;
&lt;p&gt;+94 81 2384176,&lt;br /&gt;+94 81 2386667,&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Toll Free No:&amp;nbsp;&lt;/strong&gt;+94 81 2384400&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 7845535&lt;/td&gt;
&lt;td&gt;agm_central@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Managers (Operational &amp;amp; Maintenance)&lt;/h4&gt;
&lt;table class=&quot;mtable conname&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;Name &amp;amp; Designation&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;Telephone / Fax&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;Mobile&lt;/td&gt;
&lt;td&gt;E-mail&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr.&amp;nbsp;&lt;strong style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;N. Chandrasena&lt;/strong&gt;&lt;/strong&gt;&lt;br /&gt;(Kandy - South)&lt;br /&gt;&lt;em&gt;&lt;strong&gt;Responsive Areas:&lt;/strong&gt;&lt;/em&gt; University, Udunuwara, Yatinuwara, Eriyagama, Kadugannawa, Gampola, Nawalapitiya, Nillambe, Weligalla WSS&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2389077&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal; text-align: center;&quot;&gt;+94 71 8196194&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;m_ks_central@waterboard.lk&lt;/span&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. S. Piyaratne&lt;/strong&gt;&lt;br /&gt;(Kandy - North)&lt;br /&gt;&lt;em&gt;&lt;strong&gt;Responsive Areas:&lt;/strong&gt;&lt;/em&gt; Harispaththuwa, Alawathugoda, Akurana, Galagedara, Pathadumbara WSS&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2492302,&lt;br /&gt;&lt;strong&gt;Fax:&amp;nbsp;&lt;/strong&gt;+94 81 2492303&lt;br /&gt;&lt;strong&gt;Toll Free No:&lt;/strong&gt; +94 81 2492222&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 7223738&lt;/td&gt;
&lt;td&gt;m_kn_central@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. I.C.B. Vithanage&lt;/strong&gt;&lt;br /&gt;(Kandy - East)&lt;br /&gt;&lt;em&gt;&lt;strong&gt;Responsive Areas:&lt;/strong&gt;&lt;/em&gt; Kundasale, Marassana, Tennekumbura, Medadumbara, Hantana, Ampitiyam, Rikillagaskada, Walapane, Ragala, Hatton, Maskeliya, Ginigathhena, Thalawakele, Kotagala, Poondaluoya WSS&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2420585&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 71 4198416&lt;/td&gt;
&lt;td&gt;m_ke_central@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Mr. S.M.S. Bandara&lt;/strong&gt;&lt;br style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot; /&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;(Production)&lt;/span&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2492300 &amp;nbsp; &lt;strong&gt;Fax:&lt;/strong&gt; +94 81 2492222&amp;nbsp;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 71 4814576&amp;nbsp;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. W. Jayasinghe&lt;/strong&gt;&lt;br /&gt;Manager (Human resources)&lt;br /&gt;&lt;em&gt;&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/em&gt;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2385602,&lt;br /&gt;&lt;strong&gt;Fax:&amp;nbsp;&lt;/strong&gt;+94 81 2386667&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 2442058&lt;/td&gt;
&lt;td&gt;mssc@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. R.A.C. Ariyaratne&lt;/strong&gt;&lt;br /&gt;Manager (Commercial)&lt;br /&gt;&lt;em&gt;&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/em&gt;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2385602,&lt;br /&gt;&lt;strong&gt;Fax:&lt;/strong&gt;+94 81 2386667&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 7764349, +94 71 6821598&amp;nbsp;&lt;/td&gt;
&lt;td&gt;m_co_central@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Other Sections&lt;/h4&gt;
&lt;table class=&quot;mtable conname&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td&gt;Name &amp;amp; Designation&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;Telephone / Fax&lt;/td&gt;
&lt;td style=&quot;width: 60px; text-align: center;&quot;&gt;Mobile&lt;/td&gt;
&lt;td&gt;E-mail&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mrs. N.K.B.C.D. Narasinghe&lt;/strong&gt;&lt;br /&gt;Chief Engineer (Planning &amp;amp; Design)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2374528,&lt;br /&gt;+94 81 2386667&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 71 4426923&lt;/td&gt;
&lt;td&gt;cepndcentral@waterboard.lk&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. A.M.A.M. Adikari&lt;/strong&gt;&lt;br /&gt;Chief Engineer (Development)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2387175,&lt;br /&gt;+94 81 2388027&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 071 4825182&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. H.P.K.S. Pathirana&lt;/strong&gt;&lt;br /&gt;Chief Engineer (Contruction)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2374528,&lt;br /&gt;+94 81 2386667&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 71 8298570&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;Mr. P.V.J. Fernando&lt;/strong&gt;&lt;br /&gt;Chief Engineer (Mechanical &amp;amp; Electrical)&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 81 2387175,&lt;br /&gt;+94 81 2386667&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;+94 77 34007394, +94 71 4394898&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;strong&gt;&lt;strong style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Mr. W. Jayasinghe&lt;/strong&gt;&lt;br style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot; /&gt;&lt;/strong&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Chief Engineer (Sector Planning)&lt;/span&gt;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal; text-align: center;&quot;&gt;+94 81 23888962,&lt;/span&gt;&lt;br style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal; text-align: center;&quot; /&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal; text-align: center;&quot;&gt;+94 81 2386667&lt;/span&gt;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal; text-align: center;&quot;&gt;+94 77 2442058&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;mailto:sectorplan@hotmail.com&quot;&gt;sectorplan@hotmail.com&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;

</div></div></div>
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-2" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#key-facts-and-figures-2"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Key Facts and Figures
</span></a>
</div>
<div class="accordion-body collapse" id="key-facts-and-figures-2">
<div class="accordion-inner panel-body">&lt;/p&gt;
&lt;h4&gt;Service Standard Indicators&lt;/h4&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; rowspan=&quot;2&quot;&gt;Service Indicators&amp;nbsp;&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;RSC (Central) 2014' Dec&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center; width: 200px;&quot;&gt;Regional Average&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Coverage (%) Pipe System maintained by NWSDB&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;36%&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Per Capita Consumption (l/c/d)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;108.83&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Availability (hours)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;20.3&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Water Quality - Bacteriological Quality Compliance&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Water Quality - Bacteriological Testing Compliance&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Water Quality - All Samples Compliance&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Sewerage Coverage (%)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;0.10%&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Operational Indicators&lt;/h4&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; rowspan=&quot;2&quot;&gt;Operational Indicators&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;RSC (Central) 2014'Aug&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center; width: 200px;&quot;&gt;Regional Average&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Non-Revenue Water (%)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;24%&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Non-Revenue Water - m&lt;sup&gt;3&lt;/sup&gt;/conn/day&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;0.17&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Defective Meters per '000 connections (Monthly Average)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;0&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Total Staff/ 1000 connection&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;3.93&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Operational Staff/ 1000 connection&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;3.25&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Estimated Bills/ 1000 connections (Monthly Average)&lt;/td&gt;
&lt;td align=&quot;right&quot;&gt;1&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Performance in Customer Service&lt;/h4&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; rowspan=&quot;2&quot;&gt;Customer Service Indicators&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;RSC (Central) 2014'Aug&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center; width: 200px;&quot;&gt;Regional Average&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Response to requests for new service connections (%)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;100.0%&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Customer Complaints Volume (Complaints/ 1000 connection)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;28&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Customer Complaints Resolution&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;100%&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h4&gt;Key Performance Indicators (KPIs)&lt;/h4&gt;
&lt;table class=&quot;mtable&quot; style=&quot;width: 100%;&quot; border=&quot;0&quot; cellspacing=&quot;1&quot; cellpadding=&quot;1&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center;&quot; rowspan=&quot;2&quot;&gt;Financial KPIs&lt;/td&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;RSC (Central) 2014'Aug&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;mhead&quot;&gt;
&lt;td style=&quot;text-align: center; width: 200px;&quot;&gt;Regional Average&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Collection Ratio (%)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot;&gt;96.0%&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Accounts Receivable Period (months)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;2.1&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Collectable Accounts Receivable Period (months)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;0.95&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Operating Ratio&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;1.08&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Production Cost (LKR/ m3 Produced) (Only operational cost)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;31.9&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;Average Tariff (LKR/ m&lt;sup&gt;3&lt;/sup&gt; Sold)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;37&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Stock Efficiency (LKR/ connection)&lt;/td&gt;
&lt;td style=&quot;text-align: right;&quot; align=&quot;right&quot;&gt;3,595&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 12.1599998474121px; line-height: 15.8079996109009px;&quot;&gt;

</div></div></div>
<div class="accordion-group panel">
<div class="accordion-heading panel-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#set-nn_sliders-2" href="http://waterboard.lk/web/index.php?option=com_content&view=category&id=41&Itemid=101&lang=en&format=feed&type=atom#large-scale-water-supply-amp-sanitation-projects-2"><div class="clo"></div><div class="ope"></div><span class="nn_sliders-toggle-inner">
Large Scale Water Supply &amp;amp; Sanitation Projects
</span></a>
</div>
<div class="accordion-body collapse" id="large-scale-water-supply-amp-sanitation-projects-2">
<div class="accordion-inner panel-body">&lt;/span&gt;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;Project Name&amp;nbsp;&lt;/td&gt;
&lt;td&gt;No of Beneficiaries&amp;nbsp;&lt;/td&gt;
&lt;td&gt;Total Cost Estimate (Rs.Million)&amp;nbsp;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;From&lt;/td&gt;
&lt;td&gt;To&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&amp;nbsp;Gr. Kandy Water Supply Project (pha 1, Stg 2)&lt;/td&gt;
&lt;td&gt;249,500&amp;nbsp;&lt;/td&gt;
&lt;td&gt;4,200&amp;nbsp;&lt;/td&gt;
&lt;td&gt;March 2007&amp;nbsp;&lt;/td&gt;
&lt;td&gt;2015&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Gr. Dambulla Water Supply Project&amp;nbsp;&lt;/td&gt;
&lt;td&gt;120,000&lt;/td&gt;
&lt;td&gt;10,700&amp;nbsp;&lt;/td&gt;
&lt;td&gt;2015&amp;nbsp;&lt;/td&gt;
&lt;td&gt;2015&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Gr. Matale&amp;nbsp;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Water Supply Project&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;393,317&amp;nbsp;&lt;/td&gt;
&lt;td&gt;26,834&amp;nbsp;&lt;/td&gt;
&lt;td&gt;2015&amp;nbsp;&lt;/td&gt;
&lt;td&gt;2018&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Kand North Pathadumbara&amp;nbsp;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Water Supply Project&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;470,000&lt;/td&gt;
&lt;td&gt;33,400&lt;/td&gt;
&lt;td&gt;2015&lt;/td&gt;
&lt;td&gt;2018&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;</div></div></div></div>&lt;/p&gt;</content>
		<category term="Central" />
	</entry>
	<entry>
		<title>Test cp</title>
		<link rel="alternate" type="text/html" href="http://waterboard.lk/web/index.php?option=com_content&amp;view=article&amp;id=142&amp;catid=41&amp;Itemid=101&amp;lang=en"/>
		<published>2014-10-20T01:41:12+00:00</published>
		<updated>2014-10-20T01:41:12+00:00</updated>
		<id>http://waterboard.lk/web/index.php?option=com_content&amp;view=article&amp;id=142&amp;catid=41&amp;Itemid=101&amp;lang=en</id>
		<author>
			<name>Super User</name>
			<email>sample@mail.com</email>
		</author>
		<summary type="html">&lt;p&gt;dasd&lt;/p&gt;</summary>
		<content type="html">&lt;p&gt;dasd&lt;/p&gt;</content>
		<category term="Central" />
	</entry>
</feed>
