<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! - Open Source Content Management" -->
<?xml-stylesheet href="http://waterboard.lk/web/plugins/system/osolcaptcha/osolCaptcha/captchaStyle.css" type="text/css"?>
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="ta-in">
	<title type="text">HRM &amp; IR
	<subtitle type="text">National Water Supply and Drainage Board</subtitle>
	<link rel="alternate" type="text/html" href="http://waterboard.lk"/>
	<id>http://waterboard.lk/web/index.php</id>
	<updated>2015-10-19T19:42:08+00:00</updated>
	<author>
		<name>National Water Supply and Drainage Board</name>
		<email>donotreply@waterboard.lk</email>
	</author>
	<generator uri="http://joomla.org">Joomla! - Open Source Content Management</generator>
	<link rel="self" type="application/atom+xml" href="http://waterboard.lk/web/index.php?option=com_content&amp;view=category&amp;id=38&amp;Itemid=165&amp;lang=ta&amp;format=feed&amp;type=atom"/>
	<entry>
		<title>Bacteriological Quality of Water
		<link rel="alternate" type="text/html" href="http://waterboard.lk/web/index.php?option=com_content&amp;view=article&amp;id=139&amp;catid=38&amp;Itemid=165&amp;lang=ta"/>
		<published>2014-09-29T01:00:17+00:00</published>
		<updated>2014-09-29T01:00:17+00:00</updated>
		<id>http://waterboard.lk/web/index.php?option=com_content&amp;view=article&amp;id=139&amp;catid=38&amp;Itemid=165&amp;lang=ta</id>
		<author>
			<name>piyo</name>
			<email>test@maoil.com</email>
		</author>
		<summary type="html">&lt;h6&gt;Drinking Water Quality Status&lt;/h6&gt;
&lt;p&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Bacteriological Quality of Water 2015&lt;/span&gt;&lt;/p&gt;
&lt;table class=&quot;mtable&quot; style=&quot;height: 55px; width: 662px;&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Report on Sampling and Testing (April)&amp;nbsp;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2WnFUMDV6TGtyTkk&quot;&gt;Click here&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Report on Sampling and Testing (May)&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2ZEY4NGZnWUZpZVE&quot;&gt;Click here&lt;/a&gt;&lt;span style=&quot;font-family: verdana, geneva;&quot;&gt;&lt;/span&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Report on Sampling and Testing (June)&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2VWZMS3FRQnlHeFU&quot;&gt;Click here&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h6&gt;&amp;nbsp;&lt;/h6&gt;
&lt;h6&gt;&amp;nbsp;&lt;/h6&gt;</summary>
		<content type="html">&lt;h6&gt;Drinking Water Quality Status&lt;/h6&gt;
&lt;p&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Bacteriological Quality of Water 2015&lt;/span&gt;&lt;/p&gt;
&lt;table class=&quot;mtable&quot; style=&quot;height: 55px; width: 662px;&quot;&gt;
&lt;tbody&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;Report on Sampling and Testing (April)&amp;nbsp;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2WnFUMDV6TGtyTkk&quot;&gt;Click here&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r2&quot;&gt;
&lt;td&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Report on Sampling and Testing (May)&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2ZEY4NGZnWUZpZVE&quot;&gt;Click here&lt;/a&gt;&lt;span style=&quot;font-family: verdana, geneva;&quot;&gt;&lt;/span&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr class=&quot;r1&quot;&gt;
&lt;td&gt;&lt;span style=&quot;color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: normal;&quot;&gt;Report on Sampling and Testing (June)&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2VWZMS3FRQnlHeFU&quot;&gt;Click here&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;h6&gt;&amp;nbsp;&lt;/h6&gt;
&lt;h6&gt;&amp;nbsp;&lt;/h6&gt;</content>
		<category term="Text Links" />
	</entry>
	<entry>
		<title>Safe Water Coverage</title>
		<link rel="alternate" type="text/html" href="http://waterboard.lk/web/index.php?option=com_content&amp;view=article&amp;id=138&amp;catid=38&amp;Itemid=165&amp;lang=ta"/>
		<published>2014-09-29T00:59:44+00:00</published>
		<updated>2014-09-29T00:59:44+00:00</updated>
		<id>http://waterboard.lk/web/index.php?option=com_content&amp;view=article&amp;id=138&amp;catid=38&amp;Itemid=165&amp;lang=ta</id>
		<author>
			<name>piyo</name>
			<email>test@maoil.com</email>
		</author>
		<summary type="html">&lt;p style=&quot;text-align: center;&quot;&gt;&lt;img src=&quot;http://waterboard.lk/web/images/contents/safe_water_coverage.jpg&quot; alt=&quot;safe water coverage&quot; /&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;p style=&quot;text-align: center;&quot;&gt;&lt;img src=&quot;images/contents/safe_water_coverage.jpg&quot; alt=&quot;safe water coverage&quot; /&gt;&lt;/p&gt;</content>
		<category term="Text Links" />
	</entry>
	<entry>
		<title>Supplier Registrations</title>
		<link rel="alternate" type="text/html" href="http://waterboard.lk/web/index.php?option=com_content&amp;view=article&amp;id=137&amp;catid=38&amp;Itemid=165&amp;lang=ta"/>
		<published>2014-09-29T00:59:27+00:00</published>
		<updated>2014-09-29T00:59:27+00:00</updated>
		<id>http://waterboard.lk/web/index.php?option=com_content&amp;view=article&amp;id=137&amp;catid=38&amp;Itemid=165&amp;lang=ta</id>
		<author>
			<name>piyo</name>
			<email>test@maoil.com</email>
		</author>
		<summary type="html">&lt;p&gt;Registered Suppliers for year 2015&amp;nbsp;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;DESCRIPTION&amp;nbsp;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;DOWNLOAD&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;PIPES &amp;amp; SPECIALS&lt;/strong&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Brass - Stop Cocks, ferrules, Gate Valves etc. and Gunmetal - Ferrules etc.&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2WlVGN0ZZcGYzR2s&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;CI (Cast Iron Pipes &amp;amp; Fittings, Valves, Couplings, Adaptors)&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2SU1TNEx6LXY0YVU&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;DI (Ductile Iron Pipes &amp;amp; Fittings, Valves, Couplings, Adaptors, Repair Clamps)&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2cXY1MmR0Q3Y2VUU&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;GI (Galvanized Iron Pipes &amp;amp; Fittings, Flanges)&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2SHBwdWt2blh4Y2s&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;HDPE (Pipes &amp;amp; Fittings)&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2aFNUNHhDVGw1OEk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Alkethine Pipe&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2aGFFaFo0QkJtWDQ&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Meters (Water meters, Flow meters)&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2TFdhS25udmMzd00&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Plastic water tanks etc.&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2LVp5cVNkZndrckk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;PVC Pipes &amp;amp; Fittings, Solvent Cement&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2ajg3NFA0SEtGUXc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Stainless Steel Pipes &amp;amp; Fittings&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2QXF3aTljNlZFMjQ&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Steel Pipes &amp;amp; Fittings&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2WnN2ak5FcXdsd00&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;
&lt;h5&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%;&quot;&gt;STATIONERY&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/h5&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Computer Consumables (CD's, Ribbons, Cartridges, Toners)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2SjdHXy1yNkN3ZmM&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Office and General Stationery /Papers (Computers, Photocopies) Pens, Clips, Punchers, Staplers, Toners, Master roles, etc.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2d3hPLW9qVXVVa2M&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Stationery for Planning &amp;amp; Design /Plan printing paper, P/P Toner, Tracing Paper&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bnVIMDh6azJXekU&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;EQUIPMENT&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Kitchen Utensils (Crockery, Cutlery, Water Filters, Cups &amp;amp; Saucers, Glasses, Scales etc.)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2MlFXMmFRNW9TWmc&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Office Equipment (Postal Franking Machines, Type writers, Spiral Binders, Roneo/ Duplicating Machines GPS, Photocopiers, Fax Machines, Overhead Projectors)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2YUVWZEd4ZTZnSWs&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;BUILDING CONSTRUCTION AND HARDWARE&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Building Materials (Bricks, Cement, Sand, Metal, Asbestos Sheets/ Galvanized Sheets etc. )&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bHZaZVI2d29pWFk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Sanitaryware (Wash basins, Taps, Commodes &amp;amp; Cisterns, Tiles etc.)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2eWRrYVJqaG5wQjA&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Timber Materials (Rafters, Planks, Joists, Reefers)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bzdJT2thOTFIY0U&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Construction Equipment(Wheel barrows, hand carts, Paint and Paint brushes etc.)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bWhKZ2NMVG13S0k&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Fiber Glass Items&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2dndJY3dzdXZ3dVU&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Bolts &amp;amp; Nuts, M.S. Sheets, Tor Steels, Tarpaulin etc.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2X0hWWUZfcXZhZmM&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Safety Equipment, Fire Extinguishers, Gloves, Helmets, Raincoats, Gum Boots, Masks, Road Marker Tapes, Traffic Cones etc.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2YkNzVmFraVFpLVk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;ELECTRICAL, ELECTRONIC AND IT EQUIPMENTS&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Air conditioners&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2ZTNSejV4bS1RcHc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Electrical (Refrigerators, Kettles, Heaters, Water Boilers, Vacuum Cleaner, Water Filters etc.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2eWhHWG1OWUROTjg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Electronic (Calculators, Adding Machines, Cash Registers, Finger Print Machine etc.)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2VWZmeXl6YWRsaHc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Telecommunication Equipments (Telephone systems, Mobile Phones and Key Telephones etc.)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2ZHFaVE1qRVNISzg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Computer, Computer Peripherals(Printers, UPS), Servers, Software, Networking, Audio Visual etc.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2M2JoWDdpVjhVdFk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;TOOLS&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;
&lt;p&gt;Mechanical - Welding Equipment &amp;amp; Accessories (Grinders, Diamond Cutting tool, &lt;br /&gt;Adjustable spanners Transmission Jacks, pipe wrenches, Bench wise etc.)&lt;/p&gt;
&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2dW5YWTdxS1VDOG8&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Electrical - (Hammer, Drills &amp;amp; Accessories, Cutting Pliers &lt;br /&gt;Electronic - (Pneumatic, Screwdrivers , Soldering irons, disordering Tools etc. )&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2eExOREtjQUlRTDg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;LABORATORY EQUIPMENT, CHEMICAL &amp;amp; UTILITIES&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Filter Media - Graded Sand and Pebbles etc.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2TGF1Y2szMGZkQ2s&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Laboratory Chemicals &amp;amp; Equipment&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2SE9XVF9tZ0RfRHc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Water Treatment Chemicals (Aluminium Sulphate, Bleaching powder, Hydrated Lime, Bentonite Clay, Poly Aluminium Chloride), Activated Carbon and Polymer&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2cG9aeTJBbURLMzg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;VEHICLES &amp;amp; MACHINERY, AUTOMOBILES&lt;/strong&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Automobile Batteries&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2cFRuUjZFWE1pWjA&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Machinery Equipment &amp;amp; Material Handling Equipment &amp;amp; Spares&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2cFQxQTc5R2dKY0U&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Motor Spares &amp;amp; Accessories&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2SjJtX0lON0tJNWc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Tyres &amp;amp; Tubes for vehicles&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/file/d/0BwBg25kWbLu2bU5ONkFOVVp0TDQ/view?usp=sharing&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;PUMPS, MOTORS &amp;amp; SPARES&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Pumps &amp;amp; water purification equipments, Spares for water pumps and bearings&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2Zi14MnZMR2xyQW8&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Hand Pumps and spares for hand pumps&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2cXh5ZjRNUktSUUU&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;GENERAL PURPOSE&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Rubber Products - Packing, Rings, Hoses etc.&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2R3RoenZrdmpRaGc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Textile - Dusters &amp;amp; Towels/ Flags etc.&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2QXlXZW1EOEdMaTA&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Toiletries (Soap, Disinfectants, etc.)&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2c2tXdWxRUXlZbE0&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;FURNITURE &amp;amp; FITTINGS&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Furniture (Wooden) - Tables/Chairs/ Cupboards/ File Racks etc.&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2d0lVQUdKckdfX1E&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Furniture (Steel, Plastic &amp;amp; Fiber Glass) - Tables/Chairs, Cupboards/Cabinets etc.&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2dDNDRklxR0NlZlE&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;SERVICES&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Building Construction/ Repair/ Maintenance Work&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bnJpYnFwc2dPVnc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Name Board Printing&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2Nl9mWGNSQWhKU00&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Welding Work&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2Qmx5U0V1T3lZN28&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Painting and Interior Décor (Vertical Blinds &amp;amp; Curtains etc.)&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2Z3F3T0F4cUdMZG8&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Light Weight Aluminum work (Partition work, Exterior Cladding Work, Enclosures, Doors, Windows etc.)&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2b0JXNnhOMHlpQ0E&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Hiring of Passenger Vehicles&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bktpOGRrUXItekk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Hire of Heavy Machinery (Back-hoes, Bull-dozers, Water bowsers)&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2b29kbVNrd0JRelk&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Printing of Water Bills etc.&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2VGM2N1ZjUldfWTg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Printing and Allied Services&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2LWE2ZEZJNENOWlk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Supply of Labour / Genitorial Service&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2Z0NsR0RCQ010eUE&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Surveying (Services)&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2YjNpZjNVemVxNDg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Civil Engineering Work (Laying of pipes in water supply &amp;amp; sewerage work, Construction of roads)&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2aWk2R01nS0NDOG8&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Vehicle- Repairs/Services/AC Repair/Cushion work&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2emZuanZfT2RFQUU&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;</summary>
		<content type="html">&lt;p&gt;Registered Suppliers for year 2015&amp;nbsp;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;td&gt;DESCRIPTION&amp;nbsp;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;DOWNLOAD&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;PIPES &amp;amp; SPECIALS&lt;/strong&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Brass - Stop Cocks, ferrules, Gate Valves etc. and Gunmetal - Ferrules etc.&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2WlVGN0ZZcGYzR2s&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;CI (Cast Iron Pipes &amp;amp; Fittings, Valves, Couplings, Adaptors)&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2SU1TNEx6LXY0YVU&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;DI (Ductile Iron Pipes &amp;amp; Fittings, Valves, Couplings, Adaptors, Repair Clamps)&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2cXY1MmR0Q3Y2VUU&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;GI (Galvanized Iron Pipes &amp;amp; Fittings, Flanges)&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2SHBwdWt2blh4Y2s&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;HDPE (Pipes &amp;amp; Fittings)&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2aFNUNHhDVGw1OEk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Alkethine Pipe&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2aGFFaFo0QkJtWDQ&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Meters (Water meters, Flow meters)&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2TFdhS25udmMzd00&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Plastic water tanks etc.&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2LVp5cVNkZndrckk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;PVC Pipes &amp;amp; Fittings, Solvent Cement&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2ajg3NFA0SEtGUXc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Stainless Steel Pipes &amp;amp; Fittings&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2QXF3aTljNlZFMjQ&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Steel Pipes &amp;amp; Fittings&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2WnN2ak5FcXdsd00&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;
&lt;h5&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%;&quot;&gt;STATIONERY&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/h5&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Computer Consumables (CD's, Ribbons, Cartridges, Toners)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2SjdHXy1yNkN3ZmM&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Office and General Stationery /Papers (Computers, Photocopies) Pens, Clips, Punchers, Staplers, Toners, Master roles, etc.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2d3hPLW9qVXVVa2M&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Stationery for Planning &amp;amp; Design /Plan printing paper, P/P Toner, Tracing Paper&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bnVIMDh6azJXekU&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;EQUIPMENT&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Kitchen Utensils (Crockery, Cutlery, Water Filters, Cups &amp;amp; Saucers, Glasses, Scales etc.)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2MlFXMmFRNW9TWmc&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Office Equipment (Postal Franking Machines, Type writers, Spiral Binders, Roneo/ Duplicating Machines GPS, Photocopiers, Fax Machines, Overhead Projectors)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2YUVWZEd4ZTZnSWs&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;BUILDING CONSTRUCTION AND HARDWARE&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Building Materials (Bricks, Cement, Sand, Metal, Asbestos Sheets/ Galvanized Sheets etc. )&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bHZaZVI2d29pWFk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Sanitaryware (Wash basins, Taps, Commodes &amp;amp; Cisterns, Tiles etc.)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2eWRrYVJqaG5wQjA&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Timber Materials (Rafters, Planks, Joists, Reefers)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bzdJT2thOTFIY0U&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Construction Equipment(Wheel barrows, hand carts, Paint and Paint brushes etc.)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bWhKZ2NMVG13S0k&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Fiber Glass Items&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2dndJY3dzdXZ3dVU&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Bolts &amp;amp; Nuts, M.S. Sheets, Tor Steels, Tarpaulin etc.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2X0hWWUZfcXZhZmM&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Safety Equipment, Fire Extinguishers, Gloves, Helmets, Raincoats, Gum Boots, Masks, Road Marker Tapes, Traffic Cones etc.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2YkNzVmFraVFpLVk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;ELECTRICAL, ELECTRONIC AND IT EQUIPMENTS&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Air conditioners&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2ZTNSejV4bS1RcHc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Electrical (Refrigerators, Kettles, Heaters, Water Boilers, Vacuum Cleaner, Water Filters etc.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2eWhHWG1OWUROTjg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Electronic (Calculators, Adding Machines, Cash Registers, Finger Print Machine etc.)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2VWZmeXl6YWRsaHc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Telecommunication Equipments (Telephone systems, Mobile Phones and Key Telephones etc.)&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2ZHFaVE1qRVNISzg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;Computer, Computer Peripherals(Printers, UPS), Servers, Software, Networking, Audio Visual etc.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2M2JoWDdpVjhVdFk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;TOOLS&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/strong&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;
&lt;p&gt;Mechanical - Welding Equipment &amp;amp; Accessories (Grinders, Diamond Cutting tool, &lt;br /&gt;Adjustable spanners Transmission Jacks, pipe wrenches, Bench wise etc.)&lt;/p&gt;
&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;span style=&quot;font-size: 10pt; line-height: 115%; font-family: 'Maiandra GD', sans-serif;&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2dW5YWTdxS1VDOG8&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Electrical - (Hammer, Drills &amp;amp; Accessories, Cutting Pliers &lt;br /&gt;Electronic - (Pneumatic, Screwdrivers , Soldering irons, disordering Tools etc. )&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2eExOREtjQUlRTDg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;&lt;strong&gt;LABORATORY EQUIPMENT, CHEMICAL &amp;amp; UTILITIES&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Filter Media - Graded Sand and Pebbles etc.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2TGF1Y2szMGZkQ2s&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Laboratory Chemicals &amp;amp; Equipment&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2SE9XVF9tZ0RfRHc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Water Treatment Chemicals (Aluminium Sulphate, Bleaching powder, Hydrated Lime, Bentonite Clay, Poly Aluminium Chloride), Activated Carbon and Polymer&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2cG9aeTJBbURLMzg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;VEHICLES &amp;amp; MACHINERY, AUTOMOBILES&lt;/strong&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Automobile Batteries&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2cFRuUjZFWE1pWjA&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Machinery Equipment &amp;amp; Material Handling Equipment &amp;amp; Spares&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2cFQxQTc5R2dKY0U&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Motor Spares &amp;amp; Accessories&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2SjJtX0lON0tJNWc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Tyres &amp;amp; Tubes for vehicles&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/file/d/0BwBg25kWbLu2bU5ONkFOVVp0TDQ/view?usp=sharing&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;&lt;strong&gt;PUMPS, MOTORS &amp;amp; SPARES&lt;/strong&gt;&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Pumps &amp;amp; water purification equipments, Spares for water pumps and bearings&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2Zi14MnZMR2xyQW8&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Hand Pumps and spares for hand pumps&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2cXh5ZjRNUktSUUU&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;GENERAL PURPOSE&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Rubber Products - Packing, Rings, Hoses etc.&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2R3RoenZrdmpRaGc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Textile - Dusters &amp;amp; Towels/ Flags etc.&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2QXlXZW1EOEdMaTA&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Toiletries (Soap, Disinfectants, etc.)&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2c2tXdWxRUXlZbE0&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;FURNITURE &amp;amp; FITTINGS&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Furniture (Wooden) - Tables/Chairs/ Cupboards/ File Racks etc.&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2d0lVQUdKckdfX1E&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Furniture (Steel, Plastic &amp;amp; Fiber Glass) - Tables/Chairs, Cupboards/Cabinets etc.&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2dDNDRklxR0NlZlE&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td colspan=&quot;2&quot;&gt;&lt;strong&gt;SERVICES&lt;/strong&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Building Construction/ Repair/ Maintenance Work&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bnJpYnFwc2dPVnc&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Name Board Printing&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2Nl9mWGNSQWhKU00&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Welding Work&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2Qmx5U0V1T3lZN28&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Painting and Interior Décor (Vertical Blinds &amp;amp; Curtains etc.)&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2Z3F3T0F4cUdMZG8&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Light Weight Aluminum work (Partition work, Exterior Cladding Work, Enclosures, Doors, Windows etc.)&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2b0JXNnhOMHlpQ0E&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Hiring of Passenger Vehicles&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2bktpOGRrUXItekk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Hire of Heavy Machinery (Back-hoes, Bull-dozers, Water bowsers)&lt;/td&gt;
&lt;td&gt;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2b29kbVNrd0JRelk&quot;&gt;&amp;nbsp;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Printing of Water Bills etc.&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2VGM2N1ZjUldfWTg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Printing and Allied Services&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2LWE2ZEZJNENOWlk&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Supply of Labour / Genitorial Service&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2Z0NsR0RCQ010eUE&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Surveying (Services)&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2YjNpZjNVemVxNDg&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Civil Engineering Work (Laying of pipes in water supply &amp;amp; sewerage work, Construction of roads)&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2aWk2R01nS0NDOG8&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Vehicle- Repairs/Services/AC Repair/Cushion work&lt;/td&gt;
&lt;td&gt;&amp;nbsp;&lt;a href=&quot;https://drive.google.com/uc?export=download&amp;amp;id=0BwBg25kWbLu2emZuanZfT2RFQUU&quot;&gt;Click Here..&lt;/a&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;</content>
		<category term="Text Links" />
	</entry>
</feed>
